const horses = [
    'Appaloosa',
    'Arabian',
    'Belgian',
    'Clydesdale',
    'Connemara',
    'Curly Horse',
    'Donkey',
    'Draft',
    'Friesian',
    'Gaited',
    'Grade',
    'Haflinger',
    'Icelandic Horse',
    'Lipizan',
    'Miniature Horse',
    'Missouri Foxtrotter',
    'Morgan',
    'Mule',
    'Mustang',
    'Paint / Pinto', 
    'Palomino',
    'Paso Fino',
    'Percheron',
    'Peruvian Paso',
    'Pony',
    'Pony of the Americas',
    'Quarterhorse',
    'Rocky Montain Horse',
    'Saddlebred',
    'Shetland Pony',
    'Standardbred',
    'Tenessee Walker',
    'Thoroughbred',
    'Warmblood'
]

export default horses;
